### ISSUE TITLE
movie2sdcard compilation errors

### ISSUE THREAD

**Issue by wcameron10** [PaulStoffregen/OctoWS2811#41]
### Description

In new versions of **Processing**, `myMovie` is not being initialized. I believe this is because `myMovie` is initialized outside of setup().  

**I have a fix in place and would like to submit a pull request.** 

### Steps To Reproduce Problem

`/extras/VideoSDcard/Processing/movie2sdcard.pde` will not compile with new versions of Processing(I'm on Windows 11). 

1. `git checkout origin/master -- /extras/VideoSDcard/Processing/movie2sdcard.pde`
2.  Update the paths for `myMovie` AND `FileOutputStream`
3.  Run

### Hardware & Software
Board - **Teensy 4.1**
Shields / modules used - **OctoWS2811**
Processing version - **v4.3**
Teensyduino version - **v1.58.1**
Operating system & version 
    - Windows 11 Home 
    - Version: 22H2 
    - OS Build: 22621.2715
Any other software or hardware? **n/a**

### Processing Sketch
`git checkout origin/master -- /extras/VideoSDcard/Processing/movie2sdcard.pde`

### Errors or Incorrect Output
```
Processing video library using bundled GStreamer 1.20.3
Scanning GStreamer plugins... Done.
java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at processing.core.PApplet.runSketch(PApplet.java:10074)
	at processing.core.PApplet.main(PApplet.java:9845)
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at processing.core.PApplet.runSketch(PApplet.java:10068)
	... 1 more
Caused by: java.lang.NullPointerException: Cannot invoke "processing.core.PSurface.stopThread()" because "this.surface" is null
	at processing.core.PApplet.dispose(PApplet.java:3413)
	at processing.core.PApplet.die(PApplet.java:3329)
	at processing.core.PApplet.die(PApplet.java:3339)
	at processing.video.Movie.initGStreamer(Unknown Source)
	at processing.video.Movie.<init>(Unknown Source)
	at movie2sdcard.<init>(movie2sdcard.java:71)
	... 7 more
RuntimeException: java.lang.reflect.InvocationTargetException
```

**Comment by PaulStoffregen** [comment]
Ok, please send a pull request.  I'm not using Processing in recent years, so I will have to trust you.
